package ApendixA;

import java.io.IOException;
import java.lang.annotation.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Java 8 Study Guide: Repeated Annotations + Type-Use Annotations.
 * <p>
 * This file is intentionally written as a study guide.
 * Read the comments, then run main() and inspect the examples.
 */
public class Java8AnnotationsStudyGuide {

    // ============================================================
    // 1. NORMAL DECLARATION ANNOTATIONS
    // ============================================================

    /*
     * An annotation adds metadata to a program element.
     *
     * Common examples:
     *   @Override
     *   @Deprecated
     *   @SuppressWarnings
     *   @Test
     *
     * Before Java 8, annotations mainly targeted declarations:
     * classes, methods, fields, parameters, etc.
     */

    @Deprecated
    static void oldMethod() {
        // This method is marked as deprecated.
    }

    // ============================================================
    // 2. REPEATED ANNOTATIONS
    // ============================================================

    /*
     * Before Java 8, this was NOT allowed:
     *
     * @Author(name = "Raoul")
     * @Author(name = "Mario")
     * @Author(name = "Alan")
     * class Book {}
     *
     * You would get a duplicate-annotation error.
     */

    // ---- Old workaround: explicit container annotation ----

    static void readAuthors() {
        /*
         * getAnnotationsByType() returns all repeated annotations.
         *
         * This is the important Java 8 API for repeatable annotations.
         */
        Author[] authors =
                Book.class.getAnnotationsByType(Author.class);

        Arrays.asList(authors)
                .forEach(author -> System.out.println(author.name()));
    }

    static void readAuthorsWithLoop() {
        Author[] authors =
                Book.class.getAnnotationsByType(Author.class);

        for (Author author : authors) {
            // will print "Raoul", "Mario", "Alan"
            System.out.println("Author = " + author.name());
        }
    }

    // You can also inspect the generated container directly.
    static void readContainerAnnotation() {
        Authors container =
                Book.class.getAnnotation(Authors.class);

        // will print "true" because the container is generated by the compiler
        // syntax sugar for repeated annotations.
        System.out.println("Container found = " + (container != null));

        if (container != null) {
            for (Author author : container.value()) {
                // will print "Raoul", "Mario", "Alan"
                System.out.println("From container = " + author.name());
            }
        }
    }

    // ============================================================
    // 3. MAKING AN ANNOTATION REPEATABLE IN JAVA 8
    // ============================================================

    /*
     * Step 1:
     * Add @Repeatable(ContainerAnnotation.class).
     *
     * Step 2:
     * Create the container annotation with an array value().
     */

    static void compareReflectionMethods() {
        /*
         * getAnnotation(Author.class) asks for ONE Author annotation.
         *
         * For repeated annotations, use:
         * getAnnotationsByType(Author.class)
         */
        Author one = Book.class.getAnnotation(Author.class);
        Author[] many = Book.class.getAnnotationsByType(Author.class);

        System.out.println("getAnnotation() = " + one);
        System.out.println("getAnnotationsByType().length = " + many.length);
    }

    static void variableTypeExample() {
        // The annotation applies to the use of String as a type.
        @NonNull String name = "Ahmed";

        System.out.println(name);
    }

    // ============================================================
    // 4. USING THE REPEATABLE ANNOTATION
    // ============================================================

    /*
     * Java 8 lets us write the same annotation multiple times.
     * The compiler still stores them through the container.
     */

    static void genericTypeExample() {
        // @NonNull applies to each String element in the List.
        List<@NonNull String> names = new ArrayList<>();

        names.add("Ahmed");
        names.add("Ali");

        System.out.println(names);
    }

    // Another generic example with a user-defined type.
    static void genericCarExample() {
        List<@NonNull Car> cars = new ArrayList<>();

        cars.add(new Car("BMW"));
        cars.add(new Car("Tesla"));

        System.out.println(cars);
    }

    // ============================================================
    // 5. READING REPEATED ANNOTATIONS
    // ============================================================

    static void newExpressionExample() {
        // The annotation is attached to the type used by new.
        List<@NonNull String> names =
                new @NonNull ArrayList<@NonNull String>();

        names.add("Alice");

        System.out.println(names);
    }

    static void castExample(Object value) {
        // Annotation is placed on the type inside the cast.
        String name = (@NonNull String) value;

        System.out.println(name);
    }

    static void instanceofExample(Object value) {
        // TYPE_USE annotations are allowed on the type in instanceof.
        if (value instanceof @NonNull String) {
            System.out.println("value is a String");
        }
    }

    // ============================================================
    // 6. REFLECTION: getAnnotation() VS getAnnotationsByType()
    // ============================================================

    /*
     * TYPE_USE can also annotate an exception type in a throws clause.
     */
    static void throwsExample() throws @NonNull IOException {
        throw new IOException("Study-guide example");
    }

    // ============================================================
    // 7. RETENTION POLICY
    // ============================================================

    /*
     * RetentionPolicy.RUNTIME means the annotation is available through
     * reflection while the program is running.
     *
     * For the reflection example above, BOTH:
     *   @Author
     *   @Authors
     * must use RUNTIME retention.
     */

    // ============================================================
    // 8. TYPE-USE ANNOTATIONS
    // ============================================================

    /*
     * Java 8 introduced ElementType.TYPE_USE.
     *
     * This means an annotation can be placed on a TYPE USE,
     * not only on a declaration.
     *
     * TYPE_USE can appear in places such as:
     *   - variable types
     *   - generic type arguments
     *   - new expressions
     *   - casts
     *   - instanceof checks
     *   - implements clauses
     *   - throws clauses
     */

    static void arrayExample() {
        /*
         * The exact placement matters because Java distinguishes:
         *   - the array type
         *   - the element type
         */

        @NonNull String[] names1 = {"A", "B"};

        // Another legal type-use placement:
        String @NonNull [] names2 = {"C", "D"};

        System.out.println(Arrays.toString(names1));
        System.out.println(Arrays.toString(names2));
    }

    // ============================================================
    // 9. TYPE-USE ANNOTATION ON A VARIABLE TYPE
    // ============================================================

    static void importantTypeAnnotationPoint() {
        /*
         * This is the key idea:
         *
         * @NonNull by itself does NOT prevent null.
         *
         * Java 8 gives us the syntax and metadata support.
         * A tool such as the Checker Framework can inspect the annotations
         * and perform additional static analysis.
         */

        @NonNull String name = null; // Compiles: Java itself does not enforce @NonNull.

        System.out.println(name);
    }

    // ============================================================
    // 10. TYPE-USE ANNOTATION ON A GENERIC TYPE ARGUMENT
    // ============================================================

    static void customTypeUseExample() {
        // This documents an intended rule: the value should be positive.
        @Positive Integer age = 26;

        System.out.println(age);
    }

    public static void main(String[] args) {
        System.out.println("=== Repeated annotation values ===");
        readAuthors();

        System.out.println("\n=== Reflection comparison ===");
        compareReflectionMethods();

        System.out.println("\n=== Container annotation ===");
        readContainerAnnotation();

        System.out.println("\n=== Variable type annotation ===");
        variableTypeExample();

        System.out.println("\n=== Generic type annotation ===");
        genericTypeExample();
        genericCarExample();

        System.out.println("\n=== new expression annotation ===");
        newExpressionExample();

        System.out.println("\n=== instanceof annotation ===");
        instanceofExample("hello");

        System.out.println("\n=== Array type annotation ===");
        arrayExample();

        System.out.println("\n=== Custom type-use annotation ===");
        customTypeUseExample();

        System.out.println("\n=== Old pre-Java-8 workaround ===");
        OldAuthors old =
                OldBook.class.getAnnotation(OldAuthors.class);

        if (old != null) {
            for (OldAuthor author : old.value()) {
                System.out.println(author.name());
            }
        }
    }

    // ============================================================
    // 11. TYPE-USE ANNOTATION ON new
    // ============================================================

    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface OldAuthor {
        String name();
    }

    // ============================================================
    // 12. TYPE-USE ANNOTATION ON A CAST
    // ============================================================

    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface OldAuthors {
        OldAuthor[] value();
    }

    // ============================================================
    // 13. TYPE-USE ANNOTATION ON instanceof
    // ============================================================

    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @Repeatable(Authors.class)
    @interface Author {
        String name();
    }

    // ============================================================
    // 14. TYPE-USE ANNOTATION ON implements
    // ============================================================

    /*
     * A type-use annotation can be placed on an implemented type.
     *
     * The annotation does NOT magically enforce anything.
     * A framework or static-analysis tool must understand its meaning.
     */

    // Container annotation required by @Repeatable.
    @Target(ElementType.TYPE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface Authors {
        Author[] value();
    }

    @Target(ElementType.TYPE_USE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface NonNull {
    }

    // ============================================================
    // 15. TYPE-USE ANNOTATION ON throws
    // ============================================================

    interface Vehicle {
        void drive();
    }

    // ============================================================
    // 16. TYPE-USE ANNOTATIONS WITH ARRAYS
    // ============================================================

    @Target(ElementType.TYPE_USE)
    @Retention(RetentionPolicy.RUNTIME)
    @interface Positive {
    }

    // ============================================================
    // 17. TYPE-USE ANNOTATIONS DO NOT PROVIDE CHECKING BY THEMSELVES
    // ============================================================

    // The old Java-style workaround.
    @OldAuthors({
            @OldAuthor(name = "Raoul"),
            @OldAuthor(name = "Mario"),
            @OldAuthor(name = "Alan")
    })
    static class OldBook {
    }

    // ============================================================
    // 18. SIMPLE CUSTOM TYPE-USE ANNOTATION FOR RANGE EXAMPLE
    // ============================================================

    @Author(name = "Raoul")
    @Author(name = "Mario")
    @Author(name = "Alan")
    static class Book {
    }

    // Another example with only two repeated annotations.
    @Author(name = "Joshua")
    @Author(name = "Brian")
    static class JavaBook {
    }

    // ============================================================
    // MAIN: RUN THE STUDY EXAMPLES
    // ============================================================

    static class Car implements @NonNull Vehicle {

        private final String model;

        Car(String model) {
            this.model = model;
        }

        @Override
        public void drive() {
            System.out.println(model + " is driving");
        }

        public String model() {
            return model;
        }
    }
}
