package FP;

import java.util.function.Supplier;

class LazyList<T> implements MyList<T> {
    final T head;
    final Supplier<MyList<T>> tail;
    public LazyList(T head, Supplier<MyList<T>> tail) {
        this.head = head;
        this.tail = tail;
    }

    static void main() {
        LazyList<Integer> naturals = LazyList.from(1);
        // head is 1-> tail is generated by static from
        var one = naturals.head(); // 1
        var two = naturals.tail().head(); // 2
        var three = naturals.tail().tail().head(); // 3
        System.out.println("First three naturals: " + one + ", " + two + ", " + three);

    }

    public static LazyList<Integer> from(int n) {
        return new LazyList<Integer>(n, () -> from(n + 1));
    }

    public T head() {
        return head;
    }

    public MyList<T> tail() {
        return tail.get();
    }

    public boolean isEmpty() {
        return false;
    }
}